language: java
jdk: oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY

addons:
  sonarqube:
    token:
      secure: $SONAR_TOKEN
    branches:
      - master

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar